### ISSUE TITLE
As a engineer, I have an API for retrieving information about Projects, Runs, and Responses

### ISSUE THREAD

**Issue by bjinwright** [MetaMetricsInc/loadlamb#7]
# End Goal
Creating an API that serves as a source of information for the accompanying web application.

- [ ] Create Swagger template
- [x] Create function that retrieves a list of projects
- [x] Create function that retrieves a list of runs for a particular project
- [x] Create function that returns data for a specific run
- [x] Create function that will return comparitive data between two runs
- [ ] Create deployment code

**Comment by gsmith077** [comment]
> * [x]  Create function that retrieves a list of projects
https://github.com/MetaMetricsInc/loadlamb/blob/220963d09b2ba9378343fe85c66e0fb7f4736bbf/loadlamb/api/app.py#L10-L15
> * [x]  Create function that retrieves a list of runs for a particular project
https://github.com/MetaMetricsInc/loadlamb/blob/220963d09b2ba9378343fe85c66e0fb7f4736bbf/loadlamb/api/app.py#L18-L25
> * [x]  Create function that returns data for a specific run
https://github.com/MetaMetricsInc/loadlamb/blob/220963d09b2ba9378343fe85c66e0fb7f4736bbf/loadlamb/api/app.py#L28-L44
https://github.com/MetaMetricsInc/loadlamb/blob/220963d09b2ba9378343fe85c66e0fb7f4736bbf/loadlamb/api/app.py#L47-L69
> * [x]  Create function that will return comparative data between two runs
https://github.com/MetaMetricsInc/loadlamb/blob/220963d09b2ba9378343fe85c66e0fb7f4736bbf/loadlamb/api/app.py#L72-L131

Code has been created for the listed functions, linked above.

**Comment by bjinwright** [comment]
Complete
